build:
  image: scalaplatform/scala:0.5
  environment:
    - COURSIER_CACHE=/drone/cache/coursier
  commands:
    - export PATH=$PATH:/root/local/bin
    - ./bin/testAll.sh
cache:
  mount:
    - /drone/cache
