language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
git:
  submodules: false
scala:
  - 2.11.8
before_install:
  - ./bin/setupCI.sh
script:
  - ./bin/testAll.sh
after_success:
  - codecov
jdk:
  - oraclejdk7
notifications:
  email:
    - olafurpg@gmail.com
branches:
  only:
    - master

