githubOwner: scalacenter
scala212: 2.12.4
coursierVersion: 1.0.0-RC13
name: scalafix
baseurl: /scalafix
description: Rewrite and linting tool for Scala
docsUrl: docs
highlighter: rouge
docs: true
semanticdbSbtVersion: 0.4.0
collections:
  tut:
    output: true
stableVersion: 0.5.10
scala211: 2.11.12
version: 0.5.10-20180615-2202
scalametaVersion: 2.1.7
callToActionUrl: docs/users/installation
callToActionText: Get started
supportedScalaVersions:
- 2.11.12
- 2.12.4
githubRepo: scalafix
org: ch.epfl.scala
markdown: kramdown
